# Generated by Django 4.2.3 on 2023-08-13 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="started_at",
            field=models.DateField(blank=True, db_column="END_DATE", null=True),
        ),
    ]
