# Generated by Django 4.2.3 on 2023-08-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0003_alter_post_started_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="started_at",
        ),
        migrations.AddField(
            model_name="post",
            name="started_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="started_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
