# Generated by Django 4.2.3 on 2023-08-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0004_remove_post_started_at_post_started_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="hits",
            field=models.PositiveIntegerField(default=0, verbose_name="조회수"),
        ),
    ]
