# Generated by Django 4.2.3 on 2023-08-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0005_post_hits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="hits",
        ),
        migrations.AddField(
            model_name="post",
            name="countung",
            field=models.IntegerField(default=0, verbose_name="조회수"),
        ),
    ]
