# Generated by Django 4.2.3 on 2023-08-16 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0006_remove_post_hits_post_countung"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="countung",
        ),
    ]
