# Generated by Django 4.2.3 on 2023-08-11 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="volunteer",
            field=models.BooleanField(default=False),
        ),
    ]
