# Generated by Django 4.2.3 on 2023-08-11 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="address",
            new_name="company",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="lating",
            new_name="keyword",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="navi",
            new_name="manu_f",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="phoneNumber",
            new_name="price_borrow",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="title",
            new_name="price_buy",
        ),
        migrations.RemoveField(
            model_name="product",
            name="mo_time",
        ),
        migrations.RemoveField(
            model_name="product",
            name="re_time",
        ),
        migrations.AddField(
            model_name="product",
            name="url_go",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
