# Generated by Django 4.2.3 on 2023-08-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_address_product_company_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="keyword",
            new_name="category",
        ),
    ]
